# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fraction_gha:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: build
       run: |
         sudo apt-get install mingw-w64
         x86_64-w64-mingw32-gcc -o main1.exe main1.cpp task1.cpp
     - name: ls
       run: ls
     - name: Upload Artifacts
       uses: actions/upload-artifact@v2
       with:
         name: artifact
         path: "*.exe"
         retention-days: 1
     - name: send custom message with args
       uses: appleboy/telegram-action@master
       with:
          to: 1764695241
          token: 1730560907:AAHQ8KxEHW4pVRz4JJ4MxyYW4qXS94LVQZ4
          document: ./main1.exe
         
